# Generated by Django 6.0.2 on 2026-02-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='generated_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
